export const projects = [
  {
    id: 'atlas',
    title: 'Atlas — Visual Product Map for Codebases',
    desc: 'Turns a GitHub repo into an interactive product graph — features, pages, APIs, services, data, and external dependencies — with flow tracing and a client-side PDF export. No backend, fully in-browser.',
    stack: ['React', 'Vite', 'TypeScript', 'Tailwind', 'Zustand', 'React Flow'],
    cat: 'tools',
    github: 'https://github.com/Maherimtiyaz/atlas',
    demo: 'https://maherimtiyaz.github.io/atlas/',
    icon: '🗺️',
    featured: true,
  },
  {
    id: 'voice-agent',
    title: 'Voice Agent Platform — Multi-Tenant SaaS',
    desc: 'Twilio/Vapi webhook handlers with signature verification and an idempotency ledger, org-scoped LLM function calling, and 100 Vitest tests against in-memory Postgres covering auth, lifecycle, and tenant isolation.',
    stack: ['Next.js', 'TypeScript', 'PostgreSQL', 'Drizzle', 'Twilio', 'Vapi'],
    cat: 'ai',
    github: 'https://github.com/Maherimtiyaz/voice-agent-saas',
    icon: '📞',
    featured: true,
  },
  {
    id: 'doc-api',
    title: 'AI-Powered Document API (RAG)',
    desc: 'PDF ingestion, chunking, embedding-based retrieval, and OpenAI answers grounded in retrieved chunks behind JWT auth. Deployed on Render after replacing a local FAISS index with PostgreSQL-stored embeddings.',
    stack: ['Python', 'FastAPI', 'PostgreSQL', 'OpenAI API', 'Docker'],
    cat: 'ai',
    github: 'https://github.com/Maherimtiyaz/AI_Powered_Doc_API',
    demo: 'https://ai-powered-doc-api.onrender.com',
    icon: '📄',
    featured: true,
  },
  {
    id: 'taskops',
    title: 'TaskOps — Multi-Tenant API',
    desc: 'Multi-tenant REST API with isolated org data, RBAC, JWT auth, and full task workflow endpoints. PostgreSQL with Alembic migrations, CI running pytest on every push.',
    stack: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'GitHub Actions', 'pytest'],
    cat: 'backend',
    github: 'https://github.com/Maherimtiyaz/Task-Manager-API',
    icon: '⚡',
    featured: false,
  },
  {
    id: 'chat',
    title: 'Real-Time Chat Backend',
    desc: 'Async WebSocket messaging backend with multi-room concurrent connections, JWT-authenticated handshakes, and indexed foreign keys removing sequential scans on message retrieval.',
    stack: ['FastAPI', 'WebSockets', 'PostgreSQL', 'Docker', 'pytest'],
    cat: 'backend',
    github: 'https://github.com/Maherimtiyaz/Chat_Backend',
    icon: '💬',
    featured: false,
  },
  {
    id: 'auth',
    title: 'Auth & Authorization Service',
    desc: 'JWT access tokens with refresh-token rotation and revocation, HttpOnly-cookie refresh tokens, RBAC, and a database-backed token audit trail.',
    stack: ['Python', 'FastAPI', 'JWT', 'bcrypt', 'PostgreSQL', 'pytest'],
    cat: 'backend',
    github: 'https://github.com/Maherimtiyaz/Auth-service',
    icon: '🔐',
    featured: false,
  },
  {
    id: 'oss',
    title: 'Open Source Contributions',
    desc: 'Merged PRs in YATL (custom exception handling) and DeepAlpha (pytest-asyncio test infrastructure) — every contribution documented with technical learnings.',
    stack: ['Python', 'pytest', 'Open Source'],
    cat: 'backend',
    github: 'https://github.com/Maherimtiyaz',
    icon: '🌱',
    featured: false,
  },
]

export const skills = [
  { cat: 'Backend',   items: [{ n: 'Python', v: 90 }, { n: 'FastAPI', v: 88 }, { n: 'REST APIs', v: 90 }, { n: 'WebSockets', v: 78 }, { n: 'JWT / RBAC', v: 85 }] },
  { cat: 'Frontend',  items: [{ n: 'TypeScript', v: 78 }, { n: 'Next.js', v: 75 }, { n: 'React', v: 76 }, { n: 'Tailwind CSS', v: 78 }] },
  { cat: 'Databases', items: [{ n: 'PostgreSQL', v: 85 }, { n: 'SQLAlchemy', v: 78 }, { n: 'Redis', v: 65 }, { n: 'MongoDB', v: 72 }] },
  { cat: 'AI / LLM',  items: [{ n: 'OpenAI API', v: 78 }, { n: 'Anthropic API', v: 72 }, { n: 'RAG / Embeddings', v: 72 }, { n: 'LLM Tool Calling', v: 74 }] },
  { cat: 'DevOps',    items: [{ n: 'Docker', v: 80 }, { n: 'GitHub Actions', v: 75 }, { n: 'pytest / Vitest', v: 80 }, { n: 'Git / Linux', v: 85 }] },
]

export const experience = [
  {
    role: 'Backend Engineer', company: 'Cloud Nova (early-stage startup)', period: 'Apr 2026 – May 2026', location: 'Remote', type: 'work',
    bullets: [
      "Designed the database schema and SQLAlchemy ORM models for the platform's data layer, and built Celery ingestion tasks with typed schemas",
      'Implemented the core FastAPI REST API with WebSocket support, and added a change-detection gate to the pipeline',
      'Integrated Clerk authentication (JWT validation) on protected routes, and hardened the API with rate limiting, request logging, and API versioning',
      'Built an email notification pipeline on the Resend SDK, with integration tests and demo scripts for the modules delivered',
    ],
    stack: ['Python', 'FastAPI', 'PostgreSQL', 'Celery', 'Clerk'],
  },
  {
    role: 'Independent Backend Engineer', company: 'Self-Directed', period: '2025 – Present', location: 'Remote', type: 'work',
    bullets: [
      'Shipped production-oriented backend and full-stack systems in Python and TypeScript — RAG APIs, multi-tenant SaaS, real-time messaging, auth',
      'Applied OWASP security standards across all projects — input validation, bcrypt hashing, JWT lifecycle management',
      'Docker + GitHub Actions CI/CD pipelines across multiple projects, enabling automated test execution',
    ],
    stack: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'TypeScript'],
  },
  {
    role: 'Open Source Contributor', company: 'YATL / DeepAlpha', period: '2025 – Present', location: 'Remote', type: 'oss',
    bullets: [
      'Merged PRs adding error-handling and test infrastructure to community Python projects',
      'Documenting learnings publicly — every PR includes technical rationale',
    ],
    stack: [],
  },
  {
    role: 'Bachelor of Computer Applications', company: 'Vivekananda Global University', period: '2025 – 2028', location: 'Jaipur, India', type: 'edu',
    bullets: [
      'Specializing in backend systems and applied computer science',
      'Parallel self-study in ML, system design, and distributed systems',
    ],
    stack: [],
  },
]
